version: "3"
services:
  picinguaba-api:
    container_name: 'picinguaba-api'
    build: ./backend
    ports:
      - '4000:4000'
    expose:
      - '4000'
    command: 'npm start'
    networks:
      - backend
    environment:
      MYSQL_HOST: 'picinguaba-db'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'picinguaba123'
      MYSQL_DATA: 'picinguaba'

  picinguaba-db:
    image: mysql
    container_name: 'picinguaba-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: 'picinguaba123'
      MYSQL_DATABASE: 'picinguaba'

networks:
  backend:
    driver: 'bridge'

